= FAQ
:page-title: FAQ
:description: Häufig gestellte Fragen und Antworten zu TW Forge.
:keywords: FAQ, Hilfe, Support, Probleme, Fragen

[TIP]
====
Nutze die Suche (Browser: `Strg` + `F`), um schnell Antworten auf deine Fragen zu finden.
====

== Fragen und Antworten:

=== Warum kann ich kein Stammeskonstrukt erstellen?

Während der Open Beta kann jeder Nutzer ein Stammeskonstrukt gründen - auch, wenn er bereits Mitglied eines anderen Konstrukts ist.
Bist du bereits in einem Konstrukt, findest du den Punkt *Neuer Stamm* im Stammes-Dropdown oben auf der Seite.
Häufigster Grund für eine Fehlermeldung ist ein bereits vergebener Tag: Der Tag muss auf der Welt eindeutig sein und 3 bis 6 Zeichen ohne Sonderzeichen haben (siehe xref:features/tribe-construct.adoc#gruenden[Stammeskonstrukt gründen]).

=== Warum können meine Member die Berichte nicht sehen?

Das liegt vermutlich daran, dass ihr euch entweder nicht im gleichen Konstrukt befindet, oder dass die betreffenden Member noch nicht das erforderliche Mindest-Rechtelevel (Mitglied) besitzen.
Neu angenommene Mitglieder haben immer zunächst das Level *Gast* und müssen von der Führung unter *Mitglieder* hochgestuft werden.
Für weitere Informationen zu den Berechtigungen im Stamm findest du xref:features/tribe-construct.adoc#rechtelevel[hier].

=== Warum laggt es bei mir, wenn ich im Aktionsplaner eine Aktion planen will?

Gehe sicher, dass bei dir in den Browsereinstellungen die Hardwarebeschleunigung eingeschaltet ist.

=== Warum kann meine Stammesführung meine eingetragenen Abschickzeiten / AGs nicht sehen?

Das liegt in den meisten Fällen daran, dass du dem Stammeskonstrukt in TW-Forge noch nicht beigetreten bist.

=== Mein Plan errechnet keine Angriffe, was habe ich falsch gemacht?

Hierfür kann es viele Gründe geben. Einer der häufigsten Gründe ist, dass keine Abschickzeiten angegeben sind. Dies kann durch ein Auswählen der Checkbox "Von Spielern angegebene Abschickzeiten ignorieren" unter Abschickzeiten umgangen werden.
Wurden weniger Angriffe gefunden als gewünscht, zeigt die xref:features/action-planner/calculations.adoc#ablehnungsuebersicht[Ablehnungsübersicht "Warum so wenige Angriffe?"] auf der Berechnungsseite, welche Gründe (z.B. Moral, Zeitfenster, Abhängigkeiten) dafür verantwortlich sind.

// TODO
