= FAQ
:page-title: FAQ
:description: Häufig gestellte Fragen und Antworten zu TW Forge.
:keywords: FAQ, Hilfe, Support, Probleme, Fragen

[TIP]
====
Nutze die Suche (Browser: `Strg` + `F`), um schnell Antworten auf deine Fragen zu finden.
====

== Fragen und Antworten:

=== Warum kann ich kein Stammeskonstrukt erstellen?

Man benötigt dafür einen Premium-Zugang.
Für weitere Informationen klicke xref:premium.adoc[hier].

=== Warum können meine Member die Berichte nicht sehen?

Das liegt vermutlich daran, dass ihr euch entweder nicht im gleichen Konstrukt befindet, oder dass die betreffenden Member noch nicht das erforderliche Mindest-Rechtelevel (Mitglied) besitzen.
Für weitere Informationen zu den Berechtigungen im Stamm findest du xref:features/tribe-construct.adoc#members[hier].

=== Warum laggt es bei mir, wenn ich im Aktionsplaner eine Aktion planen will?

Gehe sicher, dass bei dir in den Browsereinstellungen die Hardwarebeschleunigung eingeschaltet ist.

=== Warum kann meine Stammesführung meine eingetragenen Abschickzeiten / AGs nicht sehen?

Das liegt in den meisten Fällen daran, dass du dem Stammeskonstrukt in TW-Forge noch nicht beigetreten bist.

=== Mein Plan errechnet keine Angriffe, was habe ich falsch gemacht?

Hierfür kann es viele Gründe geben. Einer der häufigsten Gründe ist, dass keine Abschickzeiten angeben sind. Dies kann durch ein Auswählen der Checkbox "Eingetragene Abschickzeiten ignorieren" umgangen werden.

// TODO
